/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiCronSyncRouteImport } from './routes/api/cron/sync'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as UUsernameInsightsRouteImport } from './routes/u.$username.insights'
import { Route as UUsernamePickRouteImport } from './routes/u.$username.pick'
import { Route as UUsernameWrappedRouteImport } from './routes/u.$username.wrapped'
import { Route as ApiAuthDiscogsCallbackRouteImport } from './routes/api/auth/discogs/callback'
import { Route as ApiAuthDiscogsStartRouteImport } from './routes/api/auth/discogs/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameInsightsRoute = UUsernameInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernamePickRoute = UUsernamePickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameWrappedRoute = UUsernameWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => UUsernameRoute,
} as any)
const ApiAuthDiscogsCallbackRoute = ApiAuthDiscogsCallbackRouteImport.update({
  id: '/api/auth/discogs/callback',
  path: '/api/auth/discogs/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscogsStartRoute = ApiAuthDiscogsStartRouteImport.update({
  id: '/api/auth/discogs/start',
  path: '/api/auth/discogs/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/u/$username/insights': typeof UUsernameInsightsRoute
  '/u/$username/pick': typeof UUsernamePickRoute
  '/u/$username/wrapped': typeof UUsernameWrappedRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/start': typeof ApiAuthDiscogsStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/u/$username/insights': typeof UUsernameInsightsRoute
  '/u/$username/pick': typeof UUsernamePickRoute
  '/u/$username/wrapped': typeof UUsernameWrappedRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/start': typeof ApiAuthDiscogsStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/u/$username/insights': typeof UUsernameInsightsRoute
  '/u/$username/pick': typeof UUsernamePickRoute
  '/u/$username/wrapped': typeof UUsernameWrappedRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/start': typeof ApiAuthDiscogsStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u/$username'
    | '/api/auth/logout'
    | '/api/cron/sync'
    | '/u/$username/insights'
    | '/u/$username/pick'
    | '/u/$username/wrapped'
    | '/u/$username/'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/logout'
    | '/api/cron/sync'
    | '/u/$username/insights'
    | '/u/$username/pick'
    | '/u/$username/wrapped'
    | '/u/$username'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/start'
  id:
    | '__root__'
    | '/'
    | '/u/$username'
    | '/api/auth/logout'
    | '/api/cron/sync'
    | '/u/$username/insights'
    | '/u/$username/pick'
    | '/u/$username/wrapped'
    | '/u/$username/'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
  ApiAuthDiscogsCallbackRoute: typeof ApiAuthDiscogsCallbackRoute
  ApiAuthDiscogsStartRoute: typeof ApiAuthDiscogsStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/insights': {
      id: '/u/$username/insights'
      path: '/insights'
      fullPath: '/u/$username/insights'
      preLoaderRoute: typeof UUsernameInsightsRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/pick': {
      id: '/u/$username/pick'
      path: '/pick'
      fullPath: '/u/$username/pick'
      preLoaderRoute: typeof UUsernamePickRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/wrapped': {
      id: '/u/$username/wrapped'
      path: '/wrapped'
      fullPath: '/u/$username/wrapped'
      preLoaderRoute: typeof UUsernameWrappedRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/api/auth/discogs/callback': {
      id: '/api/auth/discogs/callback'
      path: '/api/auth/discogs/callback'
      fullPath: '/api/auth/discogs/callback'
      preLoaderRoute: typeof ApiAuthDiscogsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discogs/start': {
      id: '/api/auth/discogs/start'
      path: '/api/auth/discogs/start'
      fullPath: '/api/auth/discogs/start'
      preLoaderRoute: typeof ApiAuthDiscogsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UUsernameRouteChildren {
  UUsernameInsightsRoute: typeof UUsernameInsightsRoute
  UUsernamePickRoute: typeof UUsernamePickRoute
  UUsernameWrappedRoute: typeof UUsernameWrappedRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameInsightsRoute: UUsernameInsightsRoute,
  UUsernamePickRoute: UUsernamePickRoute,
  UUsernameWrappedRoute: UUsernameWrappedRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
  ApiAuthDiscogsCallbackRoute: ApiAuthDiscogsCallbackRoute,
  ApiAuthDiscogsStartRoute: ApiAuthDiscogsStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
